import React from "react";
import { Head } from "@inertiajs/react";
import AdminSidebarLayout from "@/Layouts/AdminSidebarLayout";
import { FileText, Download, Calendar, Clock } from "lucide-react";

export default function Reports({ reports }) {
    
    return (
        <AdminSidebarLayout>
            <Head title="Monthly Reports" />
            
            <div className="max-w-5xl mx-auto p-6 space-y-8">
                {/* Header */}
                <div className="bg-gradient-to-r from-purple-700 to-indigo-800 rounded-3xl p-8 text-white shadow-lg">
                    <h1 className="text-3xl font-bold mb-2">Executive Reports</h1>
                    <p className="opacity-90 max-w-2xl">
                        These reports are automatically generated by the AI System on the 1st of every month. 
                        They contain financial analysis and processor performance reviews.
                    </p>
                </div>

                {/* Reports List */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-white/10 overflow-hidden">
                    <div className="p-6 border-b border-slate-100 dark:border-white/10 flex items-center gap-2">
                        <Clock className="text-purple-600" size={20} />
                        <h2 className="font-bold text-lg text-slate-800 dark:text-white">Available Reports</h2>
                    </div>

                    {reports.length === 0 ? (
                        <div className="p-16 text-center text-slate-400">
                            <FileText size={64} className="mx-auto mb-4 opacity-30"/>
                            <p className="text-lg font-medium">No reports generated yet.</p>
                            <p className="text-sm">Wait for the 1st of next month, or run the command manually.</p>
                        </div>
                    ) : (
                        <div className="divide-y divide-slate-100 dark:divide-white/5">
                            {reports.map((report) => (
                                <div key={report.id} className="p-6 flex flex-col md:flex-row md:items-center justify-between hover:bg-slate-50 dark:hover:bg-white/5 transition gap-4">
                                    
                                    <div className="flex items-center gap-5">
                                        <div className="h-14 w-14 rounded-2xl bg-purple-50 dark:bg-purple-900/20 text-purple-600 flex items-center justify-center border border-purple-100 dark:border-purple-500/20">
                                            <FileText size={28} />
                                        </div>
                                        <div>
                                            <h3 className="font-bold text-slate-900 dark:text-white text-lg">
                                                {report.title}
                                            </h3>
                                            <div className="flex items-center gap-4 mt-1 text-sm text-slate-500">
                                                <span className="flex items-center gap-1">
                                                    <Calendar size={14} /> 
                                                    Month: {report.report_month}
                                                </span>
                                                <span className="w-1 h-1 bg-slate-300 rounded-full"></span>
                                                <span>Generated: {new Date(report.created_at).toLocaleDateString()}</span>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <a 
                                        href={route('admin.reports.download', report.id)} 
                                        className="flex items-center justify-center gap-2 px-6 py-3 bg-white dark:bg-slate-800 border border-slate-200 dark:border-white/10 hover:border-purple-500 hover:text-purple-600 dark:hover:border-purple-500 text-slate-700 dark:text-white rounded-xl font-bold text-sm transition group"
                                    >
                                        <Download size={18} className="group-hover:-translate-y-0.5 transition-transform" /> 
                                        Download PDF
                                    </a>
                                </div>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </AdminSidebarLayout>
    );
}